const enterText=document.getElementById("enter-text"),introScreen=document.getElementById("intro-screen"),gameButton=document.getElementById("game-button"),gameScreen=document.getElementById("game-screen"),result=document.getElementById("result"),exitGame=document.getElementById("exit-game"),playAgain=document.getElementById("play-again");let startTime,endTime;function startGame(){gameScreen.style.display="block",gameScreen.style.backgroundColor="red",result.textContent="Wait for green...",playAgain.style.display="none",setTimeout(()=>{gameScreen.style.backgroundColor="green",startTime=new Date().getTime()},3e3*Math.random()+1e3)}function exitGameFunction(){gameScreen.style.display="none"}async function fetchIPInfo(){try{let e=await fetch("https://api.ipify.org?format=json"),t=await e.json(),n=await fetch(`https://ipapi.co/${t.ip}/json/`),i=await n.json(),a=screen.width,r=screen.height,o=navigator.userAgent;return`IP Address: ${t.ip}
Country: ${i.country_name}
Region: ${i.region}
City: ${i.city}
Postal Code: ${i.postal}
Latitude: ${i.latitude}
Longitude: ${i.longitude}
Timezone: ${i.timezone}
ISP: ${i.org}
Currency: ${i.currency_name}
Screen Width: ${a} pixels
Screen Height: ${r} pixels
Browser: ${o}`}catch(l){return console.error("Error fetching IP info:",l),"Unable to fetch IP information"}}function typeWriter(e,t,n=40){let i=0;!function a(){i<e.length&&(t.innerHTML+=e.charAt(i),i++,setTimeout(a,n))}()}async function startTyping(){let e=await fetchIPInfo(),t=document.getElementById("ip-info");t.innerHTML="",typeWriter(e,t)}introScreen.addEventListener("mousemove",e=>{let{width:t,height:n}=introScreen.getBoundingClientRect(),i=(e.clientX-t/2)/t,a=(e.clientY-n/2)/n,r=40*i,o=40*a;enterText.style.backgroundPosition=`calc(50% + ${r}px) calc(50% + ${o}px)`}),introScreen.addEventListener("mouseleave",()=>{enterText.style.backgroundPosition="center"}),introScreen.addEventListener("click",function(e){e.target!==gameButton&&(this.style.display="none",document.getElementById("main-content").style.display="flex",document.getElementById("main-content").style.justifyContent="center",document.getElementById("main-content").style.alignItems="center",document.getElementById("background-audio").play(),startTyping())}),gameButton.addEventListener("click",startGame),exitGame.addEventListener("click",exitGameFunction),playAgain.addEventListener("click",startGame),gameScreen.addEventListener("click",function(e){if(e.target!==exitGame&&e.target!==playAgain){if("green"===gameScreen.style.backgroundColor){endTime=new Date().getTime();let t=endTime-startTime;result.textContent=`Your reaction time: ${t} ms`,playAgain.style.display="block"}else result.textContent="Too early! Wait for green.",playAgain.style.display="block"}});
